### ISSUE TITLE
Typo in the specification

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jpa-api#101]
In section 4.12 of the specification (JSR 338 JPA 2.1 Final Release for Evaluation), "wrappered" should be "wrapped".

**Comment by m-reza-rahman** [comment]
This looks like a good candidate for a community/end-user contribution. I would suggest marking it with "good first issue" and/or "help wanted". That will help facilitate recruiting people to contribute. I would honestly also mark this low priority.

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.

**Comment by tofflos** [comment]
I found the typo in section 4.12 Equality and Comparison Semantics at https://download.oracle.com/otn-pub/jcp/persistence-2_1-fr-eval-spec/JavaPersistence.pdf but it's no longer present in the master branch.

```sh
$ grep -R "Equality and Comparison Semantics" -A 10 -h
```
=== Equality and Comparison Semantics [[a5735]]

Only the values of _like_ types are permitted
to be compared. A type is _like_ another type if they correspond to the
same Java language type, or if one is a primitive Java language type and
the other is the **wrapped** Java class type equivalent (e.g., _int_ and
_Integer_ are like types in this sense). There is one exception to this
rule: it is valid to compare numeric values for which the rules of
numeric promotion apply. Conditional expressions attempting to compare
non-like type values are disallowed except for this numeric case.

**Comment by lukasj** [comment]
Let's close this then. Thanks for checking @tofflos !
