### ISSUE TITLE
Oracle JPA tutorial contains INCORRECT use of static metamodel

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jpa-api#121]
See this page
[https://docs.oracle.com/javaee/6/tutorial/doc/gjiup.html](https://docs.oracle.com/javaee/6/tutorial/doc/gjiup.html)

It says

"The following code snippet shows how to obtain the Pet entity’s metamodel class by calling Root<T>.getModel:
EntityManager em = ...;
Root<Pet> pet = cq.from(Pet.class);
EntityType<Pet> Pet_ = pet.getModel();"

Pet_ is the CANONICAL static metamodel and does NOT implement EntityType. This is utterly wrong. You get Pet_ by statically referring to it, and it is generated by an annotation processor.

The same tutorial even has
@Static Metamodel(Pet.class)
public class Pet_

{ public static volatile SingularAttribute<Pet, Long> id; public static volatile SingularAttribute<Pet, String> name; public static volatile SingularAttribute<Pet, String> color; public static volatile SetAttribute<Pet, Owner> owners; }

so it says Pet_ does not implement EntityType (and indeed is nothing to do with it).

This should be FIXED ASAP, or you will utterly confuse people

**Comment by m-reza-rahman** [comment]
This looks like a good candidate for a community/end-user contribution. I would suggest marking it with "good first issue" and/or "help wanted". That will help facilitate recruiting people to contribute. I would honestly also mark this low priority.

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.

**Comment by lukasj** [comment]
moved to https://github.com/eclipse-ee4j/jakartaee-tutorial/issues/249
