### ISSUE TITLE
Provide constants for properties

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jpa-api#139]
There are a lot of available properties, each one applicable to specific scenarios:

*   Persistence Unit level properties (persistence.xml).
*   Entity Manager level properties (EntityManager#setProperty()).
*   Query hints.

Those properties are scattered trough the spec and it's difficult to find all of them and to know which one applies to which scenario.

A simple yet very handful addition would be a class that groups all the properties and specifies its applicability in its JavaDoc.

Hibernate already does something like this: [https://github.com/hibernate/hibernate-orm/blob/0a2a5c622e3eb30724e80bc8661c0ac55ebfb2be/hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java](https://github.com/hibernate/hibernate-orm/blob/0a2a5c622e3eb30724e80bc8661c0ac55ebfb2be/hibernate-core/src/main/java/org/hibernate/cfg/AvailableSettings.java)
#### Affected Versions
[2.1.1]

**Comment by gavinking** [comment]
This would be a very good thing to do.

**Comment by gavinking** [comment]
#482 adds a list of configuration properties to `PersistenceConfiguration`.

This addresses at least the first requested item, which is, IMO, the most acute need.

In other work (#383) we've already added typesafe methods for specifying timeouts, cache modes, and the "load" graph.

The only standard hint not covered by all the above, unless I've missed something is the infamous `jakarta.persistence.fetchgraph`, which, if it were up to me, I would just deprecate.
