### ISSUE TITLE
define module name for JDK9

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jpa-api#145]
Proposal is to use 'java.persistence' to be consistence with other modules

**Comment by rbygrave** [comment]
Does it make sense for the module name to be `javax.persistence` matching the package name?  (and the expected module naming convention as I understand it).

For myself, I don't see this as part of the "JDK" so the proposal of calling it **java**.persistence does not seem obvious or correct and I'm surprised this is the proposed module name. 

What "other modules" would the module name of "java.persistence" be consistent with? Is there any thought / chance for `javax.persistence` given this is still open?

**Comment by lukasj** [comment]
The name is going to be jakarta.persistence.

**Comment by rbygrave** [comment]
Ha, ok :) ... I didn't see that coming.  Cheers :)

**Comment by lukasj** [comment]
we have jakarta.persistence
