### ISSUE TITLE
Please publish code of spec and API in this repository

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jpa-api#148]
Please publish the current spec and API _here_ in _this_ GitHub repository.

I understand that the [RI](https://github.com/eclipse/javax.persistence) is already found on GitHub [in a _separate_ GitHub organization](https://github.com/eclipse), but it would greatly support the idea of the [common javaee GitHub organization](https://github.com/javaee) if the API and spec would be _here_ instead of _there_.

**Comment by mkarg** [comment]
@mkarg I was the original reporter.

**Comment by lukasj** [comment]
I believe both is in place now
