### ISSUE TITLE
GenerationType.UUID

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jpa-api#151]
Modern applications more and more are using _replication_ technologies, inducing the problem of _global_ ID generation.

These systems tend to abstain from _central_ ID algorithms like `TABLE` or `SEQUENCE`, but instead of _UUIDs_ as PKs. The benefit is clear: The JVM of the client can produce a UUID super fast even if the network is down, and no PK clash will ever occur.

I think it would be really great particularly for cloud applications if a new `GenerationType.UUID` would instruct persistence providers to e. g. simply call JRE's `UUID.randomUUID()` method and prevent *any* network roundtrips (or providers could decide to ask for UUID from server or JDBC driver by SQL).

This is feasible and very easy to add to EclipseLink.

**Comment by mkarg** [comment]
@mkarg I was the original reporter.

**Comment by gavinking** [comment]
I think it's worth doing this and #152. In Hibernate this looks like:

```java
@Id
@GeneratedValue
UUID id;
```

And from the discussion above it looks like other products also already support it.

@lukasj Would you like me to write this up for the spec?
