### ISSUE TITLE
ElementCollection: inconsistency with example

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jpa-api#160]
http://docs.oracle.com/javaee/7/api/javax/persistence/ElementCollection.html
Specifies a collection of instances of a basic type or embeddable class.

But example:

http://docs.oracle.com/javaee/7/api/javax/persistence/MapKeyJoinColumn.html
Example 2: map key is entity for ElementCollection.

    @Entity
    public class VideoStore {
       @Id int id;
       String name;
       Address location;
       ...
       @ElementCollection
       @CollectionTable(name="INVENTORY",
                        joinColumns=@JoinColumn(name="STORE"))
       @Column(name="COPIES_IN_STOCK")
       @MapKeyJoinColumn(name="MOVIE", referencedColumnName="ID")
       Map<Movie, Integer> videoInventory;
       ...
     }

     @Entity
     public class Movie {
        @Id long id;
        String title;
        ...
     }

The question is: does ElementCollection allow element type to be Entity? Is it an association in JPA?

**Comment by m-reza-rahman** [comment]
This looks like a good candidate for a community/end-user contribution. I would suggest marking it with "good first issue" and/or "help wanted". That will help facilitate recruiting people to contribute. I would honestly also mark this low priority.

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.

**Comment by Tomas-Kraus** [comment]
Specification document defines this in chapter **11.1.14. ElementCollection Annotation**.
It says: _The ElementCollection annotation defines a collection of instances of a basic type or embeddable class._
If my fix of _basic type_ definition in PR #335 is correct, then any class that implements Serializable can also be an element of _ElementCollection_ annotated collection. And such a class can be annotated with the _@Entity_ annotation.
But in case of https://docs.oracle.com/javaee/7/api/javax/persistence/MapKeyJoinColumn.html example, class Movie does not match definition of the _basic type_ or _embeddable class_ so it shall not be an element of _ElementCollection_ annotated collection.

On the other hand that example is combined with _MapKeyJoinColumn_ annotation. In this case the specification document says that it's a valid usecase. See chapter _11.1.35. MapKeyJoinColumn Annotation_ and it's _Example 2_. It's the same example that is used in **MapKeyJoinColumn** javadoc.

**Comment by lukasj** [comment]
right, in the given example, ElementCollection applies to the Map value - Integer in this case, and MapKeyJoinColumn to the Map key - the Movie entity in this case, so this issue is invalid
