### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jpa-api#178]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by m0mus** [comment]
@radcortez You are a JPA project lead. To make the first Eclipse Glassfish release we need to finish CI/CD pipelines tasks asap. I am kindly asking you take this task or assign it to one of committers who will work on it.

**Comment by radcortez** [comment]
@m0mus sorry for some reason I've missed this notification. I'll have a look.

**Comment by radcortez** [comment]
Yeah :(

I've requested the CI here:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=539036

So now we need to wait.

**Comment by m0mus** [comment]
Update from @radcortez:
```
We got the Jenkins box up and running. Still need to add all the scripts in there.
Hope I can have sometime to do it during this week.
```

**Comment by Tomas-Kraus** [comment]
Jobs:
- master: https://jenkins.eclipse.org/jpa/job/jpa-api-master-build/
- EE4J_8: https://jenkins.eclipse.org/jpa/job/jpa-api-ee4j8-build/

**Comment by Tomas-Kraus** [comment]
@radcortez this task is done, please close it.
