### ISSUE TITLE
Release CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jpa-api#179]
This task is for creating a project release CI/CD pipeline. 

Use these documents as a reference:

- [How to release the first Eclipse version of projects](https://github.com/eclipse-ee4j/ee4j/wiki/How-to-release-the-first-Eclipse-version-of-projects)
- [JSONP release job](https://github.com/eclipse-ee4j/jsonp/wiki/JSONP-release-job)

**Comment by m0mus** [comment]
@radcortez You are a JPA project lead. To make the first Eclipse Glassfish release we need to finish CI/CD pipelines tasks asap. I am kindly asking you take this task or assign it to one of committers who will work on it.

**Comment by radcortez** [comment]
Yes.

**Comment by Tomas-Kraus** [comment]
Prepared the job on https://jenkins.eclipse.org/jpa/job/jpa-api-release/

I found some issue in Jenkins instance config, see
https://bugs.eclipse.org/bugs/show_bug.cgi?id=539036#c4
https://bugs.eclipse.org/bugs/show_bug.cgi?id=539036#c5

Job should start working when those issues are addressed.

**Comment by Tomas-Kraus** [comment]
Issues are resolved. Job was tested with master and EE4J_8 branches.

**Comment by m0mus** [comment]
Closing as done.
