### ISSUE TITLE
Support for Postgresql's Range Data Type

### ISSUE THREAD

**Issue by AbdulR3hman** [eclipse-ee4j/jpa-api#201]
Is there support for Postgresql range data types or any plans to support these features in the future?

**Comment by m-reza-rahman** [comment]
How widely is this really implemented across databases? If not very well, what is the likelihood of standardizing this in a higher level abstraction like Jakarta Persistence? I suggest closing this to reduce clutter and be able to focus on higher impact changes.

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.

**Comment by beikov** [comment]
IMO the concept of a range is widely used and often encoded as `startXXX`/`endXXX` columns/attributes. PostgreSQL just has a dedicated type for representing this which also supports overlap checking in indexes which is very useful for e.g. schedules. IMO we should maybe introduce a standard embeddable type for this concept and add some functions/predicates (`OVERLAPS`, `WITHIN`) and/or support the type in existing predicates `IN`.

**Comment by beikov** [comment]
Any reason why you close this now @AbdulR3hman? I was expressing interest in supporting this.
