### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jpa-api#202]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by m0mus** [comment]
@Tomas-Kraus please do it.

**Comment by Tomas-Kraus** [comment]
Release job passed: https://jenkins.eclipse.org/jpa/job/jpa-api-release-finalize/14/console
PR to merge release info into EE4J_8 branch: https://github.com/eclipse-ee4j/jpa-api/pull/203
