### ISSUE TITLE
Support join to unrelated entity (ad hoc joins)

### ISSUE THREAD

**Issue by reda-alaoui** [eclipse-ee4j/jpa-api#210]
It would be nice to standardize ad hoc joins introduced by [Hibernate 5.1](http://in.relation.to/2016/02/10/hibernate-orm-510-final-release/). 
That would allow us to use them with the Criteria API.

>Entity joins (or ad hoc joins)
In HQL you now have the ability to define a join to an entity, not just a mapped association. For example:

> select ...
from FinancialRecord f
    left join User u
        on r.lastUpdateBy = u.username

See [HHH-16](https://hibernate.atlassian.net/browse/HHH-16) for details.

**Comment by andyjefferson** [comment]
See https://github.com/eclipse-ee4j/jpa-api/issues/128  and close this

**Comment by reda-alaoui** [comment]
Oh I didn’t see it.
Closing.
