### ISSUE TITLE
Update Scope Statement for Jakarta Persistence API Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jpa-api#211]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by ivargrimstad** [comment]
Suggested scope statement

> Jakarta Persistence defines a standard for management of persistence and object/relational mapping in Java(TM) environments.

**Comment by waynebeaton** [comment]
Java is a registered trademark. 

> Jakarta Persistence defines a standard for management of persistence and object/relational mapping in Java(R) environments.

This looks good-to-go otherwise. Can I get a +1 from the project team?
