### ISSUE TITLE
Change project name to Jakarta Persistence

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jpa-api#212]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [ ]  GitHub
- [ ]  README file
- [ ]  CONTRIBUTING file
- [x]  Eclipse Project under https://projects.eclipse.org/projects/ee4j

**Comment by m0mus** [comment]
Jakarta Persistence sounds good.

**Comment by lukasj** [comment]
+1
