### ISSUE TITLE
Prepare Jakarta Persistence for the Jakarta EE 8 Release

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jpa-api#218]
### Instructions

- [x] Update text files
- [x] Generate "boilerplate" specification project
- [x] Make a staging release
- [x] Generate Stand-alone TCK test results
- [x] Submit a PR to jakartaee/specifications repository
- [x] Update the Jakarta EE API jar by submitting a PR to the [jakartaee-api](https://github.com/eclipse-ee4j/jakartaee-api) project

See [here](https://wiki.eclipse.org/How_to_Prepare_API_Projects_to_Jakarta_EE_8_Release) for detailed instructions.

**Comment by m0mus** [comment]
Reopening because new tasks were added.

**Comment by m0mus** [comment]
Jakarta EE API PR: https://github.com/eclipse-ee4j/jakartaee-api/pull/13
