### ISSUE TITLE
Compatibility certification request for EclipseLink

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jpa-api#228]
- [x] Organization Name ("Organization") and, if applicable, URL
Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable)
[EclipseLink 2.7.4](https://www.eclipse.org/eclipselink/downloads/ri.php)
- [x] Specification Name, Version and download URL
[Jakarta Persistence 2.2](https://jakarta.ee/specifications/persistence/2.2/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL
[Jakarta Persistence TCK 2.2.0](https://download.eclipse.org/jakartaee/persistence/2.2/eclipse-persistence-tck-2.2.0.zip), SHA-256: 96eeeceea5a6343fbd6c4e2f7b6a5aefb0b64f4dc3c4cf7d2ec68652fde2318d
- [x]  Public URL of TCK Results Summary
[TCK results summary](https://www.eclipse.org/eclipselink/releases/tck-summary.php)
- [x] Any Additional Specification Certification Requirements
None
- [x] Java runtime used to run the implementation
Oracle JDK 1.8.0_202
- [x] Summary of the information for the certification environment, operating system, cloud, ...
Apache Derby 10.14.2.0, Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the EFTL.
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by bshannon** [comment]
This certification request needs the `certification` label, which needs to be added
to this issue tracker along with the other required labels in the table at the end of
the [operations document](https://github.com/jakartaee/specification-committee/blob/master/operations.adoc).

**Comment by scottmarlow** [comment]
Should https://github.com/eclipse-ee4j/jpa-api/blob/master/api/pom.xml#L27 be changed to 2.2?

**Comment by bshannon** [comment]
No, 2.2.3 is the correct version for the API jar file.  There were several previous releases of the API jar file corresponding to version 2.2 of the spec.

**Comment by m0mus** [comment]
+1
