### ISSUE TITLE
JPA Spec contradiction on mixing input parameter types

### ISSUE THREAD

**Issue by dazey3** [eclipse-ee4j/jpa-api#238]
JPA Spec, Section 3.10.11 **Parameter Objects**:
```
The mixing of [javax.persistence.]Parameter objects with named or positional parameters is undefined.
```

JPA Spec, Section 3.10.12 **Named Parameters**:
```
The mixing of named and positional parameters is undefined.
```

JPA Spec, Section 3.10.17.1 **Named Stored Procedure Queries**:
```
If parameter names are not specified, it is assumed that positional parameters are used. 
The mixing of named and positional parameters is undefined
```

JPA Spec, Section 4.6.4: **Input Parameters**:
```
Either positional or named parameters may be used. Positional and named parameters must not be mixed in a single query.
```

---

Sections 3.10.11, 3.10.12, & 3.10.17.1, which govern the _Query_ & _StoredProcedureQuery_ APIs, seem to describe that the mixing of named and positional parameters is not defined by the spec and is open to implementation by the persistence provider.

Section 4.6.4, which governs the JPA query language, seems to describe that mixing positional and named parameters cannot be done in a single query.

These sections seem to be in contradiction. You could read this as positional and named cannot be mixed within a conditional expression, but is undefined anywhere else... but that also seems counter intuitive and messy. 

---

JDBC Spec, 4.1, Section 13.3.2: **Setting Parameters**:
```
It is not possible to combine setting parameters with ordinals and with names in the same statement. 
If ordinals and names are used for parameters in the same statement, an SQLException is thrown.
```

Considering the JDBC Spec prohibits mixing indexed and named parameters in the same statement, I submit that the JPA spec should be updated to prohibit it as well. Alternatively, Section 4.6.4 of the JPA spec should be updated to be in line with the rest of the spec.

**Comment by m-reza-rahman** [comment]
This looks like a good candidate for a community/end-user contribution. I would suggest marking it with "good first issue" and/or "help wanted". That will help facilitate recruiting people to contribute. I would honestly also mark this low priority. Perhaps it can simply be independently/fairly evaluated and closed?

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.
