### ISSUE TITLE
Give the option to embed JPA annotations into other annotations

### ISSUE THREAD

**Issue by michaelisvy** [eclipse-ee4j/jpa-api#239]
# Summary

Would it be possible to add the target `ElementType.ANNOTATION_TYPE` to JPA Annotations such as `@Id`, `@GeneratedValue`, `@Column`... ?

# Detailed explanation
Every time I create a new JPA entity, I need to declare the `id` as follows:

```java
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private Long id;
```

It would be nice to be able to create a single annotation that embeds both annotations. I would use it that way:

```java
@MyCompanyId
private Long id;
```

and declare the annotation as follows:

```java
@Target({ElementType.ANNOTATION_TYPE, ElementType.FIELD, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
public @interface MyCompanyId {
}
```

Would it make sense?

Best regards,
Michael.

**Comment by andyjefferson** [comment]
You mean Java "meta annotations"? Like is part of JPA 2.2 already, just that maybe they haven't publicised it. But good for you you can read the docs for DataNucleus who do publicise it http://www.datanucleus.org:15080/products/accessplatform_5_2/jpa/annotations.html#meta_annotations

**Comment by michaelisvy** [comment]
hi Andy,
thanks for the pointer. 
I see meta-annotations are indeed available at the class level indeed. However you can't do it at the attribute level like in the example I've shown above. Would it be possible to add that feature?

Regards,
Michael.

**Comment by andyjefferson** [comment]
Look at the last line on that link I posted.

**Comment by michaelisvy** [comment]
well, it depends on the target type on the annotation. For instance, in the case of @Id we have:
```java
@Target({METHOD, FIELD})
@Retention(RUNTIME)
public @interface Id {}
```
In order for @Id to be used as a meta-annotation, it would need to include a target type of `ElementType.ANNOTATION_TYPE`.

**Comment by andyjefferson** [comment]
Yes, you're right. Been doing it in DataNucleus for so long I forgot the situation of what actually got into JPA 2.2 (very little) and what is provided by a provider (a lot more). Your issue is a duplicate of https://github.com/eclipse-ee4j/jpa-api/issues/43. This was implemented in DataNucleus early 2017 ... but doubt it will see light of day in any spec while Oracle are anywhere near it

**Comment by michaelisvy** [comment]
ah I'm sorry, I thought this was the github repository for the JPA spec.
Since I've seen it was moved to the Eclipse foundation and your URL has Eclipse and jpa-api in the name. Apology for that :).

**Comment by andyjefferson** [comment]
This *is* the GitHub repo for the JPA API and spec. And your issue is a dup of the one I referenced in the same issue tracker. This one needs closing, and any comments putting on the other issue.

**Comment by michaelisvy** [comment]
understood, thanks for the clarification!
