### ISSUE TITLE
Cleanup JPA Specification Document

### ISSUE THREAD

**Issue by jgrassel** [eclipse-ee4j/jpa-api#245]
The JPA Specification document under `jpa-api/spec` looks like it is in really tough shape compared to previous released versions of the document (ie, 2.2 and prior).  The TOC, and much of the contents need a great deal of formatting work.

**Comment by jgrassel** [comment]
@lukasj Has there someone who's been assigned to work on this?  I looked through the list of open issues and didn't spot anything that resembled continued specification document work.

**Comment by lukasj** [comment]
@m0mus mentioned he is doing something. It would be perhaps good to split the main document into chapters so more people can work on this...

**Comment by m0mus** [comment]
Let me finish myself.

**Comment by lukasj** [comment]
assuming this is done.
