### ISSUE TITLE
address feedback from the PR #255 

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jpa-api#268]
major areas:
* formatting
* finish javax->jakarta transition
* javadoc in code and spec should match
* new schema in spec

**Comment by viswanadhk** [comment]
made some minor changes to formatting in spec.adoc in my local and trying to verify "mvn verify -B -V -Poss-release -Dgpg.skip=true" ... got a build error
ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.1:jar (attach-javadocs) on project jakarta.persistence-api: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - javadoc: error - invalid flag: --frames
[ERROR] 
[ERROR] Command line was: /usr/local/opt/openjdk/bin/javadoc @options @argfile

Anyone saw this before?

**Comment by lukasj** [comment]
use jdk 11, not older, not newer for now...

I'll fix it in a while...

**Comment by lukasj** [comment]
@viswanadhk it's going to be fixed by #270

**Comment by viswanadhk** [comment]
thanks...openjdk11 worked but just fyi I see lot of warnings...
[WARNING] /Users/vishykasinadhuni/Documents/vishy-eclipse-foundation-development/jpa-api/api/src/main/java/jakarta/persistence/criteria/CriteriaBuilder.java:843: warning: no @param for <C>
[WARNING] <E, C extends Collection<E>> Predicate isMember(E elem, Expression<C> collection);
[WARNING] ^

Thanks

**Comment by lukasj** [comment]
#270 is in master. As for warnings - some of them are unfortunately not so easy to fix :-/

**Comment by jgrassel** [comment]
Hello, looking at a build of the doc from a recent commit, I noticed 

`Copyright (c) 2019 Eclipse Foundation.`

Should that be `2020`?

**Comment by lukasj** [comment]
@jgrassel  https://github.com/eclipse-ee4j/jpa-api/blob/master/spec/src/main/asciidoc/license-efsl.adoc says ‘2019, 2020’. Are we looking st the same file?

**Comment by jgrassel** [comment]
Presumably so.  Here's a screen cap of the html doc (viewing) that I generated this morning from d9ddcb3a:

![image](https://user-images.githubusercontent.com/28658988/93384394-62e96800-f82a-11ea-99ee-5dcb6824e223.png)

**Comment by lukasj** [comment]
@jgrassel that is not the final version of the spec document (your version probably has wrong definition of orm.xsd); use the head from [main](https://github.com/github/renaming)

**Comment by lukasj** [comment]
I belive this is done
