### ISSUE TITLE
Split the specification document

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jpa-api#271]
Currently the source of the spec document has some 30k lines leading to pdf with >600 pages.

To allow more people to work together on the spec at the same time, the doc should be split into smaller parts, preferably one file per chapter/appendix for now

**Comment by moghaddam** [comment]
As you know I just started working on the spec and I'm completely agree with you. Currently it's not easy to navigate in that file. I can do the split while converting the spec to Jakarta EE.

**Comment by viswanadhk** [comment]
one file per chapter means almost 12 splits now. The main point is consistency. As long as the formatting consistency remains the same, I think we can split.

**Comment by moghaddam** [comment]
I finished the splitting and its PR (#273) is waiting for review.

**Comment by lukasj** [comment]
fixed by #273, thanks!
