### ISSUE TITLE
Update orm_3_0.xsd to refer to https://jakarta.ee/xml/ns/persistence/orm/orm_3_0.xsd

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jpa-api#286]
Update documentation in https://github.com/eclipse-ee4j/jpa-api/blob/master/api/src/main/resources/jakarta/persistence/orm_3_0.xsd#L43 to refer to https://jakarta.ee/xml/ns/persistence/orm/orm_3_0.xsd instead of https://jakarta.ee/xml/ns/persistence/orm_3_0.xsd

**Comment by lukasj** [comment]
fixed by #287
