### ISSUE TITLE
Completion Steps for Persistenced 3.0

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jpa-api#296]
Specification Committee Mentor

- [x] creates an issue in the specification project that includes the following checklist for the specification project team
Specification Project Team

 - [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] approve the compatibility request.
 - [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by lukasj** [comment]
this has been already done
