### ISSUE TITLE
[TCK] JPA persistence.xml referencing non existing jar files.

### ISSUE THREAD

**Issue by jeanouii** [eclipse-ee4j/jpa-api#299]
I’m back into TomEE regarding TCK failures .... Here is one where I’d like some feedback.
The test is com.sun.ts.tests.jpa.ee.packaging.jar.Client --> https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jpa/ee/packaging/jar/Client.java

It’s failing because the JPA provider can’t find the jar-file from the persistence.xml
I opened the EAR file used by the test (see bellow).
![image](https://user-images.githubusercontent.com/1233474/100906165-2ba16380-34c9-11eb-9f27-4f5a3c01f4f7.png)

The persistence effectively has 2 jar-file entries. But if you look at the file name on the right side in the persistence.xml and you also look at the left side to the content of the EAR file, you can see that the filename in the persistence.xml file has “_jarfile” before the number 1 or 2.

See https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jpa/ee/packaging/jar/build.xml on how the EAR file with the jar files are created.

What do you think?
How can this even work with Glassfish?

EclipseLink fails by default with the following

```
Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-28018] (Eclipse Persistence Services - 2.7.4.v20190115-ad5b7c6b2a): org.eclipse.persistence.exceptions.EntityManagerSetupException Exception Description: Predeployment of PersistenceUnit [CTS-EM] failed. Internal Exception: java.lang.RuntimeException: java.io.FileNotFoundException: /home/.../javaee8tck/dist/com/sun/ts/tests/jpa/ee/packaging/jar/jpa_ee_packaging_jar_vehicles/lib/jpa_ee_packaging_jar_jarfile1.jar (No such file or directory) at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.createPredeployFailedPersistenceException(EntityManagerSetupImpl.java:2106) at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.predeploy(EntityManagerSetupImpl.java:2082) at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactoryImpl(PersistenceProvider.java:350) at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactory(PersistenceProvider.java:316)
```

Here is what glassfish is doing ...

            if (jarFile.exists()) {
                try {
                    jarFiles.add(jarFile.toURI().toURL());
                } catch (MalformedURLException e) {
                    throw new RuntimeException(e);
                }
            } else {
                // Should be a caught by verifier. So, just log a message
                if (logger.isLoggable(Level.WARNING)) {
                    logger.log(Level.WARNING, "puinfo.referenced_jar_not_found", new Object[]{absolutePuRoot, jarFileName, jarFile});
                }
            }

Which means that as soon as a jar-file does not exist, Glassfish yanks the file. Not sure what it is actually deploying. Maybe something incomplete that may fail at runtime which I think isn't good.

Wildfly might be doing the same, not sure. But Apache TomEE passes everything to EclipseLink. It does not "fix" or remove information from the persistence.xml. It passes everything to the JPA provider and it will fail with EclipseLink which is was I would expect as a user.

The spec says

> One or more JAR files may be specified using the jar-file elements instead of, or in addition to the mapping files specified in the mapping-file elements. If specified, these JAR files will be searched for managed persistence classes, and any mapping metadata annotations found on them will be processed, or they will be mapped using the mapping annotation defaults defined by this specification. Such JAR files are specified relative to the directory or jar file that contains the root of the persistence unit.

To me, it should fail (and that's what eclipselink does) as soon as the file does not exist.
If that is the case, the test should be excluded from the TCK until we can fix the packaging.

As per https://jakarta.ee/committees/specification/tckprocess the 'challenge' label needs to be used for TCK challenges.

**Comment by scottmarlow** [comment]
I might have more input but for now I will listen, other than ask for a bit more information to be supplied below... 

> Challenges MUST be filed via the specification project’s issue tracker using the label challenge and include the following information:
> 
>     The relevant specification version and section number(s)

Please confirm that you are creating this challenge for Jakarta Persistence 3.0.

From the linked test source, the section number can be derived from `assertion_ids: PERSISTENCE:SPEC:957` which is mentioned in https://raw.githubusercontent.com/eclipse-ee4j/jakartaee-tck/master/internal/docs/jpa/Persistence22SpecAssertions.xml:
```
        <assertion required="true" impl-spec="false" defined-by="technology"
                   status="active" testable="true">
            <id>PERSISTENCE:SPEC:957</id>
            <description>One or more jar files may be specified using the
                jar-file elements instead of, or in addition
                to the mapping files specified in the mapping-files elements.
                If specified, these JAR files will be searched for managed
                persistence classes and any mapping
                metadata annotations found on them will be processed or they
                will be mapped using the mapping annotation
                defaults defined by this specification.
                Such JAR files are specified relative to the directory or jar
                file that contains the root of the
                persistence unit.
            </description>
            <location chapter="8" section="2.1.6.3"/>
        </assertion>
```
That points to https://jakarta.ee/specifications/persistence/3.0/jakarta-persistence-spec-3.0.html#jar-files (under section `8.2.1.6. mapping-file, jar-file, class, exclude-unlisted-classes`).

> 
>     The coordinates of the challenged test(s)

I think this is already provided above via https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jpa/ee/packaging/jar/Client.java.

> 
>     The exact TCK version

@jeanouii Please supply.

> 
>     The implementation being tested, including name and company

@jeanouii Please supply.

> 
>     A full description of why the test is invalid and what the correct behavior is believed to be

@jeanouii is there anything that you want to add?

> 
>     Any supporting material; debug logs, test output, test logs, run scripts, etc.

@jeanouii please attach the .jtr file for each failing test.  This is important if the test(s) are excluded.

**Comment by jeanouii** [comment]
I think we can close the issue. The TCK has been fixed with the PR already merged
