### ISSUE TITLE
Automatic entity validation for Container Constaints, doesn't work

### ISSUE THREAD

**Issue by kronos72it** [eclipse-ee4j/jpa-api#303]
I need to validate a JPA entity Transaction) with custom constraint when receiving a List<Transaction> . Then I create a Custom Constraint Annotation:
`@Target({ ElementType.TYPE,ElementType.TYPE_USE })
@Retention(RUNTIME)
@Documented
@Constraint(validatedBy = { TransactionValidator.class})
public @interface TransactionValid {

   String message() default "{org.hibernate.validator.referenceguide.chapter06.classlevel." +
        "ValidPassengerCount.message}";

   Class<?>[] groups() default { };

   Class<? extends Payload>[] payload() default { };

   LoadValues type() default LoadValues.MOV;

   @interface List {
     TransactionValid[] value();
   }
}`
And referenced Validator :
`public class TransactionValidator implements ConstraintValidator<TransactionValid,Transaction>{ 

@Override
public void initialize(TransactionValid constraintAnnotation) {
    //throw new UnsupportedOperationException("Not supported yet."); 
}

@Override
public boolean isValid(Transaction t, ConstraintValidatorContext context) {
    try {
        ValidatorObject<Transaction> validator=new TransactionValidatorLogic();
        validator.validate(t);
    } 
    catch (ConstraintViolations ex) {
        for (String s :ex.getViolations())
            context.buildConstraintViolationWithTemplate(s).addConstraintViolation();
        return false;
    }
    
    return true;
    
}

}`

Then , in my EJB I have the method receiving the List of Transaction :
`public void loadTransactions(List<@TransactionValid Transaction> q,final DataInfo info) throws HBException { 
// some other stufs
try{
        for (Transaction t : q){
            em.persist(t);
        }
    }
    catch (Exception e){
        if (e instanceof ConstraintViolationException){
    }
....
}`

Now I am expecting to get a breakpoint on my Custom Validator but it seams no Validation take place .

Thi is an EAR project with EJB and WEB modules . IN the EJB pom I used :

`<dependency>
        <groupId>jakarta.platform</groupId>
        <artifactId>jakarta.jakartaee-api</artifactId>
        <version>9.0.0</version>
        <scope>provided</scope>
</dependency>
`

And my persistence.xml is :
`<?xml version="1.0" encoding="UTF-8"?>
  <persistence version="3.0" xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://jakarta.ee/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_3_0.xsd">
  <persistence-unit name="HB_PU" transaction-type="JTA">
<provider>org.eclipse.persistence.jpa.PersistenceProvider</provider>
<validation-mode>AUTO</validation-mode>
<jta-data-source>jdbc/hb_ds_admin</jta-data-source>
<! -- some class listed -->
<exclude-unlisted-classes>true</exclude-unlisted-classes>
<properties>
  <property name="eclipselink.target-database" value="MySQL"/>
</properties>
</persistence-unit>
</persistence>`

As you cans see I added the property  **validation-mode**  though it is not needed states the [Jakarta Persistence Specification 3.0 ](https://jakarta.ee/specifications/bean-validation/3.0/jakarta-bean-validation-spec-3.0.html#constraintdeclarationvalidationprocess-containerelementconstraints).The specifiaction states that by default the AUTO value is setted and by the way the validation Bootstrap will be done by Container looking in the List and applying the Validation to all item in the List ,then what I am wrong ? it is a bug ? 
If I apply the @TransancionValid annotation to Transaction Entity this working correct and fire up my Validator.
Elsewhere ,I doen't see any validation in debugging ,any breakpoint stop on Validator!

**Comment by lukasj** [comment]
Why do you think this is a problem of the specification and not a problem of the persistence implementation you use?

> And my persistence.xml is :
```
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="3.0" xmlns="http://java.sun.com/xml/ns/persistence"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://jakarta.ee/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_3_0.xsd">
```

Have you had a chance to validate the document? This is invalid. See [the schema](https://jakarta.ee/xml/ns/persistence/persistence_3_0.xsd)

```
<provider>org.eclipse.persistence.jpa.PersistenceProvider</provider>
```

so you are using EclipseLink. In that case, the issue should have been reported at https://github.com/eclipse-ee4j/eclipselink


> As you can see I added the property validation-mode though it is not needed states the Jakarta Persistence Specification 3.0 .

I'm confused. The link called `Jakarta Persistence Specification 3.0` points to `Jakarta Bean Validation specification`. Is https://jakarta.ee/specifications/persistence/3.0/jakarta-persistence-spec-3.0.html#a2374 the correct target of the link?

Also note that automatic validation by persistence provider can happen if and only if there is `PrePersist`, `PreUpdate` or `PreRemove` annotation, see [the spec](https://jakarta.ee/specifications/persistence/3.0/jakarta-persistence-spec-3.0.html#automatic-validation-upon-lifecycle-events) - I do not see any in the code you have provided.

Based on that, I'm closing this here. Feel free to file an issue against the implementation if you believe there is a problem on that end providing compilable/runnable sample to reproduce it. Thanks!

**Comment by kronos72it** [comment]
Ok ,sorry for error about linking ... 
I will open issue to eclipse link  , I supposed EclipseLink was the default embedded provider for Jakarta EE 9 reference impl.
Anyway it doesn't work neither providing a PrePersist method.
Thanks
