### ISSUE TITLE
missing definition of single_valued_embeddable_object_field in the spec

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jpa-api#307]
JPQL BNF contains usages of `single_valued_embeddable_object_field` but this term is not defined anywhere in the spec. The closest to this seems to be `single_valued_object_field` being defined in [section 4.4.4.1](https://jakarta.ee/specifications/persistence/3.0/jakarta-persistence-spec-3.0.html#path-expression-syntax) as:
> A single_valued_object_field is designated by the name of an association field in a one-to-one or many-to-one relationship or a field of embeddable class type. The type of a single_valued_object_field is the abstract schema type of the related entity or embeddable class.

when looking for the history of this, the term was introduced between Persistence 2.0 EFD and PFD together with the definitions for embeddables etc. Since this was based on [EJB 3.0 spec](https://jcp.org/en/jsr/detail?id=220) (JSR 220), looking there reveals following definition (section 4.4.4, page 84):
> An embedded_class_state _field is designated by the name of an entity state field that corresponds to an
embedded class

based on that, I think, following definition should be added to section 4.4.4.1 of the current spec:
> An single_valued_embeddable_object_field is designated by the name of an entity state field that corresponds to an
embedded class

/cc @dazey3

**Comment by dazey3** [comment]
@lukasj 

Thank you for opening this issue and pursuing a fix in the specification! I discovered this issue while looking into https://github.com/eclipse-ee4j/eclipselink/issues/1058, but I was focused more on the fix in EclipseLink than fixing the specification.

Looking at the current BNF definition for JOINs, we have the following:
```
join_association_path_expression ::=
    join_collection_valued_path_expression |
    join_single_valued_path_expression

join_collection_valued_path_expression::= 
    identification_variable.{single_valued_embeddable_object_field.}*collection_valued_field

join_single_valued_path_expression::=
    identification_variable.{single_valued_embeddable_object_field.}*single_valued_object_field
```

Section 4.4.4.1 defines 'single_valued_object_field':
```
A 'single_valued_object_field' is designated by the name of an association field in a one-to-one or
many-to-one relationship or a field of embeddable class type. The type of a
single_valued_object_field is the abstract schema type of the related entity or embeddable class.
```

With this change, Section 4.4.4.1 will define 'single_valued_embeddable_object_field':
```
A 'single_valued_embeddable_object_field' is designated by the name of a field of embeddable class type
```

**Comment by dazey3** [comment]
I have also opened #308 to address another issue I see in section 4.4.4

**Comment by lukasj** [comment]
btw: this was also observed by hibernate back in 2009, see https://hibernate.atlassian.net/browse/HHH-4584

**Comment by dazey3** [comment]
@lukasj Nice find! I suppose this is a bridge others have already crossed historically. Not sure I see what the ultimate decision was for Hibernate, but it looks like maybe they decided to support it and chalk it up to provider specific behavior.

**Comment by m-reza-rahman** [comment]
This seems like low-hanging fruit that could be looked at in the next release and resolved one way or the other? Thoughts?

Reza Rahman
Jakarta EE Ambassador, Author, Blogger, Speaker

Please note views expressed here are my own as an individual community member and do not reflect the views of my employer.
