### ISSUE TITLE
current LocalTime, LocalDate, and LocalDateTime in queries

### ISSUE THREAD

**Issue by gavinking** [eclipse-ee4j/jpa-api#317]
Currently the JPA spec defines `current_date`, `current_time`, and `current_timestamp`, which have been interpreted by implementations to be of type `java.sql.Date`, `java.sql.time`, and `java.sql.Timestamp` respectively (even though it seems that the JPA spec leaves this unspecified!).

The problem is that `java.sql.Date`, `java.sql.time`, and `java.sql.Timestamp` are essentially deprecated and replaced by the types in `java.time`.

Hibernate 6 supports the syntax 

- `local date`, `local time`, and `local datetime`, along with
- `local_date`, `local_time`, and `local_datetime`

 which are considered to have type `LocalTime`, `LocalDate`, and `LocalDateTime` respectively.

I prefer the versions without the underscores because they look more consistent with the rest of the language, which doesn't use underscores anywhere (e.g. we don't write `order_by` or `inner_join`, nor do we write `alias.created_time` to refer to a field of an entity).

I believe that similar functionality should be added to the JPA spec.

An alternative approach would be to introduce some sort of setting which changed the interpretation of the existing syntax `current_date`, `current_time`, and `current_timestamp`, but I think this option is inferior.

Thoughts?

**Comment by m-reza-rahman** [comment]
This looks like a good, sound enhancement that dovetails nicely with what is happening in Java SE. I hope it makes it into the next specification revision.

**Comment by gavinking** [comment]
(Note that as a subtask of this issue, we would clarify the types of datetime expressions.)

**Comment by beikov** [comment]
Sounds good to me!
