### ISSUE TITLE
What PersistenceProvider class must I use for Jakarta EE 9.1?

### ISSUE THREAD

**Issue by hendrelouw73** [eclipse-ee4j/jpa-api#333]
What provider must I specify in the persistence.xml file for Jakarta EE 9.1? I get the following error with no provider provided;

```
Nov 17, 2021 2:31:45 PM jakarta.persistence.spi.PersistenceProviderResolverHolder$DefaultPersistenceProviderResolver log
WARNING: jakarta.persistence.spi::No valid providers found.
```

**Comment by lukasj** [comment]
depends on which compatible implementation you want to use. Can be for example `org.eclipse.persistence.jpa.PersistenceProvider` or `org.hibernate.jpa. HibernatePersistenceProvider`.
