### ISSUE TITLE
Unique index creation 

### ISSUE THREAD

**Issue by dreab8** [eclipse-ee4j/jpa-api#361]
The `com/sun/ts/tests/jpa/se/schemaGeneration/annotations/index/Client.java#indexTest` test checks for the unique index creation that the generated schema creation script contains 
`ALTER TABLE SCHEMAGENSIMPLE ADD UNIQUE INDEX SCHEMAGENSIMPLE_SVALUE3` or `CREATE UNIQUE INDEX SCHEMAGENSIMPLE_SVALUE3 ON SCHEMAGENSIMPLE (SVALUE3) ` and it fails if
`ALTER TABLE SCHEMAGENSIMPLE ADD CONSTRAINT SCHEMAGENSIMPLE_SVALUE3 UNIQUE (SVALUE3)` is generated instead.

**Comment by scottmarlow** [comment]
@dreab8 as mentioned in https://jakarta.ee/committees/specification/tckprocess/, this issue needs the `challenge` label to initiate a TCK challenge.

**Comment by beikov** [comment]
Note that we can't add a challenge label to the issue

**Comment by scottmarlow** [comment]
As per https://jakarta.ee/committees/specification/tckprocess, approval is the default after 14 days (March 4 I think), unless the challenge is accepted/denied before then.

**Comment by lukasj** [comment]
I believe this is purely TCK issue and since it has been resolved there already, time to close this.

**Comment by beikov** [comment]
Sure, but we would like the challenge to be accepted so that we can exclude the test from the 3.0 TCK

**Comment by lukasj** [comment]
you don't see the label added about an hour ago?

**Comment by beikov** [comment]
Sorry, I didn't look careful enough before. All fine :)

**Comment by lukasj** [comment]
ok
