### ISSUE TITLE
JPA 3.1 spec doc "Appendix A: Revision History" missing most of 3.1's changes.

### ISSUE THREAD

**Issue by jgrassel** [eclipse-ee4j/jpa-api#365]
A build of the JPA Specification doc for tag `3.1-3.1.0-RELEASE` has the following `Appendix A: Revision History` entry for Jakarta Persistence 3.1:

```
A.3. Jakarta Persistence 3.1
EntityManagerFactory and EntityManager interfaces extend java.lang.AutoCloseable interface 
Fixed ClassTransformer.transform to throw Persistence API specific exception
Added support for GenerationType.UUID
```

It is missing the following other changes which went into the spec:
* Adds CEILING, EXP, FLOOR, LN, POWER, ROUND, and SIGN numeric functions to Jakarta Persistence QL and ceiling(), exp(), floor(), ln(), power(),  round(), and sign() to Criteria API
* Adds LOCAL DATE, LOCAL DATETIME, and LOCAL TIME functions to Jakarta Persistence QL and
corresponding localDate(), localDateTime(), and localTime() to Criteria API
* Adds EXTRACT function to Jakarta Persistence QL
* Adds support for Expressions as conditions in Criteria CASE expressions
* Adds missing definition of single_valued_embeddable_object_field in Jakarta Persistence QL BNF
* Clarifies mixing types of query input parameters
* Clarifies definition of the Basic type
* Clarifies the order of parameters in the LOCATE function
* Clarifies SqlResultSetMapping with multiple EntityResults and conflicting aliases

**Comment by lukasj** [comment]
see https://jakarta.ee/specifications/persistence/3.1/jakarta-persistence-spec-3.1.html#jakarta-persistence-3-1
