### ISSUE TITLE
Broken links for TCK 3.0.2

### ISSUE THREAD

**Issue by beikov** [eclipse-ee4j/jpa-api#367]
I was curious if the 3.0.2 version of the TCK was already released and saw that at least the links have been updated, but unfortunately are broken: https://jakarta.ee/specifications/persistence/3.0/

**Comment by scottmarlow** [comment]
We can ask on jakarta.ee-spec@eclipse.org, I'll try asking soon.

**Comment by beikov** [comment]
This is fixed now. Thanks!
