### ISSUE TITLE
JPA next should support Java 8 Date and Time types

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jpa-api#63]
Currently, JPA temporal fields are supported for the following data types: <tt>java.util.Date</tt>, <tt>java.util.Calendar</tt>, <tt>java.sql.Date</tt>, <tt>java.sql.Time</tt>, and <tt>java.sql.Timestamp</tt>. <tt>java.sql.Date</tt> properties are always mapped to the JDBC methods <tt>getDate</tt> and <tt>setDate</tt>, and it is an error to specify the <tt>@javax.persistence.Temporal</tt> annotation for these types. The same is true of <tt>Time</tt> (mapped to <tt>getTIme</tt> and <tt>setTime</tt>) and <tt>Timestamp</tt> (mapped to <tt>getTimestamp</tt> and <tt>setTimestamp</tt>). Properties of type <tt>java.util.Date</tt> and <tt>Calendar</tt> must be annotated with <tt>@Temporal</tt> to specify the <tt>javax.persistence.TemporalType</tt> enum indicating which JDBC methods should be used for those properties.

Some vendors support other temporal types, such as Joda Time, but this is non-standard and should probably remain so since Joda Time isn't guaranteed to stay around (and, in fact, is likely to start ramping down with the release of Java 8).

JSR-310 as part of Java 8 specifies a new Date & Time API in the <tt>java.time</tt> package and sub-packages that supplants <tt>java.util.Date</tt>, <tt>Calendar</tt>, <tt>java.sql.Date</tt>, <tt>Time</tt>, <tt>Timestamp</tt>, and Joda Time. It is based off of the Joda Time API, but with enhancements and certain redesigns that the Joda Time founder/creator has said makes it superior to Joda Time.

JPA's existing rules for the currently-supported temporal types should remain largely unchanged. However, the specification should be added to in order to specify support for JSR-310\. These are the proposed new rules I believe should be present in the JPA.next specification:

*   Properties of type <tt>java.time.Duration</tt> are treated as <tt>@javax.persistence.Basic</tt> fields. They automatically map to;
    *   <tt>DURATION</tt> fields if the database vendor supports duration types;
    *   <tt>DECIMAL</tt>-type fields storing the seconds before the decimal point and the nanoseconds after the decimal point;
    *   <tt>INTEGER</tt>-type fields storing the seconds; and,
    *   <tt>CHAR</tt>/<tt>VARCHAR</tt>-type fields storing the value in its ISO-8601 format (<tt>Duration#toString()</tt> and <tt>Duration#parse(CharSequence)</tt>).
*   Properties of type <tt>java.time.Period</tt> are treated as <tt>@Basic</tt> fields. They automatically map to:
    *   <tt>PERIOD</tt> or <tt>DURATION</tt> fields if the database vendor supports period or duration types;
    *   <tt>DECIMAL</tt>-type fields storing the seconds before the decimal point and the nanoseconds after the decimal point;
    *   <tt>INTEGER</tt>-type fields storing the seconds; and,
    *   <tt>CHAR</tt>/<tt>VARCHAR</tt>-type fields storing the value in its ISO-8601 format (<tt>Period#toString()</tt> and <tt>Period#parse(CharSequence)</tt>).
*   Properties of type <tt>java.time.Year</tt> are treated as <tt>@Basic</tt> fields. They automatically map to:
    *   <tt>YEAR</tt> fields if the database vendor supports year types; and,
    *   <tt>INTEGER</tt>/<tt>CHAR</tt>/<tt>VARCHAR</tt>-type fields storing the literal number/string value.
*   Properties of enum type <tt>java.time.Month</tt> are treated as special-case enum fields.
    *   If the database field is a <tt>MONTH</tt> field (assuming the database vendor supports such types), it maps to this field.
    *   If <tt>@javax.persistence.Enumerated</tt> is not present and the database field is an <tt>INTEGER</tt>-type field, it maps as the month number (NOT the ordinal) using <tt>int Month#getValue()</tt> and <tt>Month Month#of(int)</tt>.
    *   Otherwise, it falls back to standard enum mapping rules.
    *   It is an error to annotate a <tt>Month</tt> property with <tt>@Enumerated</tt> if the database field is of type <tt>MONTH</tt>.
*   Properties of enum type <tt>java.time.DayOfWeek</tt> are treated as special-case enum fields.
    *   If the database field is a <tt>DAY_OF_WEEK</tt> field (assuming the database vendor supports such types), it maps to this field.
    *   If <tt>@Enumerated</tt> is not present and the database field is an <tt>INTEGER</tt>-type field, it maps as the day number (NOT the ordinal) using <tt>int DayOfWeek#getValue()</tt> and <tt>DayOfWeek DayOfWeek#of(int)</tt>.
    *   Otherwise, it falls back to standard enum mapping rules.
    *   It is an error to annotate a <tt>DayOfWeek</tt> property with <tt>@Enumerated</tt> if the database field is of type <tt>DAY_OF_WEEK</tt>.
*   Properties of type <tt>java.time.YearMonth</tt> are treated as <tt>@Basic</tt> fields.
    *   By default, they automatically map to:
        *   <tt>YEARMONTH</tt> fields if the database vendor supports year-month types;
        *   <tt>DATE</tt> and <tt>DATETIME</tt> fields storing the lowest day number that the database vendor supports and zero-time if applicable; and,
        *   <tt>CHAR</tt>/<tt>VARCHAR</tt>-type fields storing the value in its ISO-8601 format (<tt>YearMonth#toString()</tt> and <tt>YearMonth#parse(CharSequence)</tt>).
    *   The new <tt>@javax.persistence.YearMonthColumns</tt> annotation can map a <tt>YearMonth</tt> property to two database fields. A property annotated with this overrides the default mapping behavior. It is an error to mark properties of any other type with this annotation. The required <tt>@javax.persistence.Column</tt>-typed <tt>year</tt> attribute specifies the column that the year is stored in while the required <tt>@Column</tt>-typed <tt>month</tt> attribute specifies the column that the month is stored in. The year column follows the same default mapping rules as for <tt>Year</tt> types and the month column as for the <tt>Month</tt> enum. It is an error to specify <tt>@Column</tt> and <tt>@YearMonthColumns</tt> on the same property.
*   Properties of type <tt>java.time.MonthDay</tt> are treated as <tt>@Basic</tt> fields.
    *   By default they automatically map to:
        *   <tt>MONTHDAY</tt> fields if the database vendor supports month-day types;
        *   <tt>DATE</tt> and <tt>DATETIME</tt> fields storing the lowest year number that the database vendor supports and zero-time if applicable; and,
        *   <tt>CHAR</tt>/<tt>VARCHAR</tt>-type fields storing the value in its ISO-8601 format (<tt>MonthDay#toString()</tt> and <tt>MonthDay#parse(CharSequence</tt>).
    *   The new <tt>@javax.persistence.MonthDayColumns</tt> annotation can map a <tt>MonthDay</tt> property to two database fields. A property annotated with this overrides the default mapping behavior. It is an error to mark properties of any other type with this annotation. The required <tt>@Column</tt>-typed <tt>month</tt> attribute specifies the column that the month is stored in while the required <tt>@Column</tt>-typed <tt>day</tt> attribute specifies the column that the day is stored in. The month column follows the same default mapping rules as for the <tt>Month</tt> enum and the day column automatically maps to <tt>INTEGER</tt>/<tt>CHAR</tt>/<tt>VARCHAR</tt>-type fields. It is an error to specify <tt>@Column</tt> and <tt>@MonthDayColumns</tt> on the same property.
*   Properties of type <tt>java.time.ZoneId</tt> are treated as <tt>@Basic</tt> fields. They automatically map to:
    *   <tt>TIMEZONE</tt> fields if the database vendor supports time zone types (they never map to offset fields); and,
    *   <tt>CHAR</tt>/<tt>VARCHAR</tt>-type fields storing the value in its ISO-8601 format (<tt>ZoneId#toString()</tt> and <tt>ZoneId#of(String)</tt>).
*   Properties of type <tt>java.time.ZoneOffset</tt> are treated as <tt>@Basic</tt> fields. They automatically map to:
    *   <tt>OFFSET</tt> fields if the database vendor supports offset types (they never map to time zone fields); and,
    *   <tt>CHAR</tt>/<tt>VARCHAR</tt>-type fields storing the value in its ISO-8601 format (<tt>ZoneOffset#toString()</tt> and <tt>ZoneOffset#of(String)</tt>).
*   Properties of types <tt>java.time.Instant</tt>, <tt>java.time.LocalDate</tt>, <tt>java.time.LocalTime</tt>, <tt>java.time.LocalDateTime</tt>, <tt>java.time.OffsetTime</tt>, <tt>java.time.OffsetDateTime</tt>, and <tt>java.time.ZonedDateTime</tt> are treated as temporal <tt>@Basic</tt> types that are mapped using the following rules:
    *   <tt>LocalDate</tt> always maps as a date-only value. It is an error to mark a <tt>LocalDate</tt> property with the <tt>@Temporal</tt> annotation.
    *   <tt>LocalTime</tt> and <tt>OffsetTime</tt> always map as time-only values. It is an error to mark a <tt>LocalTime</tt> or <tt>OffsetTime</tt> property with the <tt>@Temporal</tt> annotation.
    *   <tt>Instant</tt>, <tt>LocalDateTime</tt>, <tt>OffsetDateTime</tt>, and <tt>ZonedDateTime</tt> map as timestamp values by default. You may mark a property of one of these types with <tt>@Temporal</tt> to specify a different strategy for persisting that property.
    *   The new <tt>@javax.persistence.TemporalIncludeTimeZone</tt> annotation indicates that the offset in the <tt>OffsetTime</tt> or <tt>OffsetDateTime</tt> property or the time zone in the <tt>ZonedDateTime</tt> or <tt>Calendar</tt> property will be persisted with the value. Otherwise (if this is absent) the value is converted to the database server offset or time zone for persistence.
    *   The new <tt>@javax.persistence.TemporalTimeZoneColumn(@Column value)</tt> annotation indicates a different column in which the time zone value is stored. It implies <tt>@TemporalIncludeTimeZone</tt>. It is required if <tt>@TemporalIncludeTimeZone</tt> is present but the database vendor does not support storing the time zone with the field data type. It is also required if <tt>@TemporalIncludeTimeZone</tt> is present but the JDBC driver in use is less than version 4.2 (a JDBC 4.2 driver is necessary to persist time zones and offsets with time/date-time values). The persistence rules for this column are the same as for <tt>ZoneId</tt> and <tt>ZoneOffset</tt> properties.
    *   Properties of these types invoke the following special handling for JDBC driver versions before and after 4.2.
        *   A JDBC driver is considered version 4.2 or better if <tt>java.sql.Driver#getMajorVersion()</tt> returns a number greater than 4, or it returns 4 and <tt>Driver#getMinorVersion()</tt> returns a number greater than 1\. In the absence of a testable <tt>Driver</tt> instance, implementations may assume that the driver version is less than 4.2 _**if**_ <tt>PreparedStatement#setObject(int, Object, SQLType)</tt> throws a <tt>SQLFeatureNotSupportedException</tt>.
        *   If the JDBC driver is version 4.2 or newer, these seven types are persisted and retrieved as follows:
            *   They are persisted with <tt>PreparedStatement#setObject(int, Object, SQLType)</tt> and retrieved with <tt>ResultSet#getObject(int, Class<?>)</tt> or <tt>ResultSet#getObject(String, Class<?>)</tt>.
            *   Time-only properties or <tt>TemporalType.TIME</tt> properties use a <tt>java.sql.SQLType</tt> of <tt>java.sql.JDBCType.TIME</tt> in the absence of <tt>@TemporalIncludeTimeZone</tt> _or_ presence of <tt>@TemporalTimeZoneColumn</tt>. They use <tt>JDBCType.TIME_WITH_TIMEZONE</tt> in the presence of <tt>@TemporalIncludeTimeZone</tt> _and_ absence of <tt>@TemporalTimeZoneColumn</tt>.
            *   Date-only properties or <tt>TemporalType.DATE</tt> properties use a <tt>SQLType</tt> of <tt>JDBCType.DATE</tt>.
            *   Date-and-time properties use a <tt>SQLType</tt> of <tt>JDBCType.TIMESTAMP</tt> in the absence of <tt>@TemporalIncludeTimeZone</tt> _or_ presence of <tt>@TemporalTimeZoneColumn</tt>. They use <tt>JDBCType.TIMESTAMP_WITH_TIMEZONE</tt> in the presence of <tt>@TemporalIncludeTimeZone</tt> _and_ absence of <tt>@TemporalTimeZoneColumn</tt>.
        *   If the JDBC driver is version 4.1 or older, these seven types are persisted and retrieved as follows:
            *   Time-only properties or <tt>TemporalType.TIME</tt> properties are automatically converted to and from <tt>Time</tt> and use the traditional <tt>setTime</tt> and <tt>getTime</tt> methods.
            *   Date-only properties or <tt>TemporalType.DATE</tt> properties are automatically converted to and from <tt>java.sql.Date</tt> and use the traditional <tt>setDate</tt> and <tt>getDate</tt> methods.
            *   Date-and-time properties are automatically converted to and from <tt>Timestamp</tt> and use the traditional <tt>setTimestamp</tt> and <tt>getTimestamp</tt> methods.
            *   <tt>@TemporalTimeZoneColumn</tt> is required if <tt>@TemporalIncludeTimeZone</tt> is present.

**Comment by barrrettt** [comment]
guys i need UTC instant for my backend, Come on!
