### ISSUE TITLE
EntityManager(Factory) should implement AutoCloseable

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jpa-api#77]
<tt>EntityManager</tt> and <tt>EntityManagerFactory</tt> have <tt>#close()</tt> methods but do not implement <tt>AutoCloseable</tt>. Implementing <tt>AutoCloseable</tt> would allow them to be used in Java 7 try-with-resource statement.

**Comment by MalteMagnussen** [comment]
I've been working a lot with EntityManager in school now, and it kinda bugs me that this isn't implemented. 
It isn't a big deal though, I just add a finally { em.close } to all my stuff, but it would be lovely if we could use try-with-resources. 
Please get this implemented.

**Comment by nerdglitchtiff** [comment]
It would be great if we could use the try-with-resource statement with the EntityManager Factory Interface. It's the only thing that makes sense.

**Comment by gavinking** [comment]
+1

**Comment by joeltoby** [comment]
+1

**Comment by DSEyers** [comment]
+1
