### ISSUE TITLE
Introduce scroll as alternative to getResultList

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jpa-api#89]
Since Java 8 was much about streams, parallelism and so on, I guess it only makes sense to extends <tt>javax.persistence.Query</tt> to also offer a method, that returns something like hibernates [<tt>org.hibernate.ScrollableResults</tt>](https://docs.jboss.org/hibernate/core/4.2/javadocs/org/hibernate/ScrollableResults.html).
Since Java 8 introduced <tt>Stream</tt> JPA could introduce something like a <tt>ResultStream</tt> that additionally supports scrolling.
This would make it possible to use JPA for **big** amounts of **data** ![](https://java.net/jira/images/icons/emoticons/smile.gif)

**Comment by beikov** [comment]
I guess this can be closed now since #99 was part of JPA 2.2?

**Comment by gavinking** [comment]
> I guess this can be closed now since #99 was part of JPA 2.2?

Since @beikov was the original reporter of this issue, and he's satisfied, I'm going to close it.
